version: 0.1
downloads:
  - name: shfmt
    executable: true
    downloads:
      - os:
          linux: linux
          macos: darwin
        cpu:
          x86_64: amd64
          arm_64: arm64
        url: https://github.com/mvdan/sh/releases/download/v${version}/shfmt_v${version}_${os}_${cpu}
      - os:
          windows: windows
        cpu:
          x86_64: amd64
        url: https://github.com/mvdan/sh/releases/download/v${version}/shfmt_v${version}_${os}_${cpu}.exe
tools:
  definitions:
    - name: shfmt
      download: shfmt
      shims: [shfmt]
      known_good_version: 3.13.1
lint:
  definitions:
    - name: shfmt
      files: [shell]
      description: A shell formatter
      commands:
        - name: format
          output: shfmt
          run: shfmt -w -s ${target}
          success_codes: [0, 1]
          cache_results: true
          formatter: true
          batch: true
          in_place: true
      tools: [shfmt]
      suggest_if: files_present
      affects_cache: [.editorconfig]
      known_good_version: 3.13.1
      version_command:
        parse_regex: ${semver}
        run: shfmt --version
