version: 0.1
downloads:
  - name: actionlint
    version: 1.17.0
    downloads:
      - os:
          linux: linux
          macos: darwin
        cpu:
          x86_64: amd64
          arm_64: arm64
        url: https://github.com/kjanat/actionlint/releases/download/v${version}/actionlint_${version}_${os}_${cpu}.tar.gz
      - os:
          windows: windows
        cpu:
          x86_64: amd64
          arm_64: arm64
        url: https://github.com/kjanat/actionlint/releases/download/v${version}/actionlint_${version}_${os}_${cpu}.zip
tools:
  definitions:
    - name: actionlint
      download: actionlint
      shims: [actionlint]
      known_good_version: 1.17.0
lint:
  definitions:
    - name: actionlint
      files: [github-workflow]
      # Custom parser/trigger type defined in the trunk cli.
      tools: [actionlint]
      description: Verify your Github workflows
      commands:
        - name: lint
          output: actionlint
          run: actionlint -format "{{json .}}" ${target}
          success_codes: [0, 1]
      suggest_if: files_present
      environment:
        - name: PATH
          list: ["${linter}", "${env.PATH}"]
      direct_configs:
        - .github/actionlint.yaml
        - .github/actionlint.yml
      issue_url_format: https://github.com/kjanat/actionlint/blob/master/docs/checks.md
      known_good_version: 1.17.0
      version_command:
        parse_regex: ${semver}
        run: actionlint --version
