name: mismatched version comment

on:
  push:

permissions: {}

jobs:
  test:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.2
        with:
          persist-credentials: false
