#!/usr/bin/env node

const yargs = require('yargs');
const path = require('path');
const fs = require('fs');

const args = yargs
  .usage('Usage: file-fixer <files...>')
  .demandCommand(1)
  .argv;

const files = args._

console.log('fixing:');
files.map(file => {
  console.log('  ' + file);
  // const content = fs.readFileSync(file, 'utf8');
  // fs.writeFileSync(file, Buffer.from(content.replace(/\r\n/g, '\n'), 'utf8'));
});
console.log('done');
